// data.js - App Data, Constants, and Design Tokens

// ============== DESIGN TOKENS ==============

export const COLORS = {
  primary: '#E63946',
  secondary: '#457B9D',
  black: '#1A1A2E',
  white: '#FFFFFF',
  background: '#F8F9FA',
  card: '#FFFFFF',
  text: '#1A1A2E',
  textLight: '#6B7280',
  border: '#E5E7EB',
  error: '#EF4444',
  success: '#10B981',
  golden: '#F59E0B',
  mapMarker: '#E63946',

  // Gray scale
  gray50: '#F9FAFB',
  gray100: '#F3F4F6',
  gray200: '#E5E7EB',
  gray300: '#D1D5DB',
  gray400: '#9CA3AF',
  gray500: '#6B7280',
  gray600: '#4B5563',
  gray700: '#374151',
  gray800: '#1F2937',
  gray900: '#111827',
};

export const SPACING = {
  xxs: 2,
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  xxxl: 64,
};

export const RADIUS = {
  sm: 6,
  md: 10,
  lg: 16,
  xl: 24,
  full: 9999,
};

export const SHADOWS = {
  sm: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  md: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  lg: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
    elevation: 6,
  },
  xl: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 10,
  },
};

export const IMAGE_HEIGHT = 220;

// ============== CATEGORIES ==============

export const CATEGORIES = [
  { id: 'all', label: 'All', icon: 'globe-outline' },
  { id: 'beach', label: 'Beaches', icon: 'sunny-outline' },
  { id: 'history', label: 'History', icon: 'library-outline' },
  { id: 'culture', label: 'Culture', icon: 'color-palette-outline' },
  { id: 'nature', label: 'Nature', icon: 'leaf-outline' },
  { id: 'city', label: 'Cities', icon: 'business-outline' },
];

// ============== TOURIST PLACES ==============

export const TOURIST_PLACES = [
  {
    id: '1',
    name: 'Sidi Bou Said',
    location: 'Tunis',
    region: 'Grand Tunis',
    category: 'culture',
    rating: 4.8,
    reviews: 2340,
    price: 'Gratuit',
    duration: '2-3 heures',
    description: 'Village pittoresque aux maisons bleu et blanc dominant la mer Méditerranée. Un des sites les plus photographiés de Tunisie, avec ses ruelles pavées et ses cafés traditionnels.',
    shortDescription: 'Iconic blue and white village above the Mediterranean.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Sidi_Bou_Said_-_TN_-_26.7.2013.jpg/1280px-Sidi_Bou_Said_-_TN_-_26.7.2013.jpg',
    features: ['Vue panoramique', 'Architecture unique', 'Café des Nattes', 'Artisanat local'],
    coordinates: { lat: 36.8705, lng: 10.3417 },
  },
  {
    id: '2',
    name: 'Carthage',
    location: 'Tunis',
    region: 'Grand Tunis',
    category: 'history',
    rating: 4.6,
    reviews: 3120,
    price: '12 DT',
    duration: '2-4 heures',
    description: 'Ancienne capitale de l\'empire carthaginois, Carthage est classée au patrimoine mondial de l\'UNESCO. Ses ruines impressionnantes témoignent d\'une civilisation millénaire.',
    shortDescription: 'UNESCO World Heritage ancient Phoenician city ruins.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/CarthagoRuins.jpg/1280px-CarthagoRuins.jpg',
    features: ['Site UNESCO', 'Musée', 'Thermes romains', 'Amphithéâtre'],
    coordinates: { lat: 36.8525, lng: 10.3233 },
  },
  {
    id: '3',
    name: 'Djerba',
    location: 'Médenine',
    region: 'Sud Tunisie',
    category: 'beach',
    rating: 4.7,
    reviews: 4560,
    price: '20-50 DT',
    duration: '3-7 jours',
    description: 'L\'île de Djerba, surnommée l\'île des rêves, offre des plages de sable blanc, une architecture traditionnelle unique et une culture séculaire mêlant influences arabes et berbères.',
    shortDescription: 'Dream island with white sand beaches and rich culture.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Djerba_Houmt_Souk_04.jpg/1280px-Djerba_Houmt_Souk_04.jpg',
    features: ['Plages', 'Medina', 'Synagogue Ghriba', 'Sports nautiques'],
    coordinates: { lat: 33.8075, lng: 10.8451 },
  },
  {
    id: '4',
    name: 'Médina de Tunis',
    location: 'Tunis',
    region: 'Grand Tunis',
    category: 'culture',
    rating: 4.5,
    reviews: 5670,
    price: 'Gratuit',
    duration: '3-4 heures',
    description: 'Classée au patrimoine mondial de l\'UNESCO, la médina de Tunis est un labyrinthe fascinant de ruelles animées, de souks colorés et de monuments islamiques remarquables.',
    shortDescription: 'UNESCO-listed medieval medina with vibrant souks.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Tunis_Medina_2.jpg/1280px-Tunis_Medina_2.jpg',
    features: ['Souk El Attarine', 'Grande Mosquée Zitouna', 'Artisanat', 'Street food'],
    coordinates: { lat: 36.7992, lng: 10.1699 },
  },
  {
    id: '5',
    name: 'Sahara de Douz',
    location: 'Kébili',
    region: 'Sud Tunisie',
    category: 'nature',
    rating: 4.9,
    reviews: 1890,
    price: '50-100 DT',
    duration: '2-3 jours',
    description: 'Porte du Sahara, Douz offre des dunes de sable dorées à perte de vue. Une expérience inoubliable de bivouac sous les étoiles et de randonnée à dos de dromadaire.',
    shortDescription: 'Gateway to the Sahara with golden dunes and camel rides.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Sahara_Desert.jpg/1280px-Sahara_Desert.jpg',
    features: ['Dunes de sable', 'Bivouac', 'Dromadaires', 'Festival du Sahara'],
    coordinates: { lat: 33.4603, lng: 9.0225 },
  },
  {
    id: '6',
    name: 'El Djem',
    location: 'Mahdia',
    region: 'Centre Tunisie',
    category: 'history',
    rating: 4.8,
    reviews: 2780,
    price: '10 DT',
    duration: '1-2 heures',
    description: 'L\'amphithéâtre d\'El Djem est l\'un des mieux conservés du monde romain. Ce colosse de 30 000 places est classé au patrimoine mondial de l\'UNESCO.',
    shortDescription: 'One of the world\'s best-preserved Roman amphitheatres.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/El_Jem-_Roman_Amphitheater_2.jpg/1280px-El_Jem-_Roman_Amphitheater_2.jpg',
    features: ['Amphithéâtre romain', 'Musée archéologique', 'Festival international', 'Site UNESCO'],
    coordinates: { lat: 35.2967, lng: 10.7067 },
  },
  {
    id: '7',
    name: 'Hammamet',
    location: 'Nabeul',
    region: 'Cap Bon',
    category: 'beach',
    rating: 4.5,
    reviews: 6230,
    price: '20-30 DT',
    duration: '3-7 jours',
    description: 'Station balnéaire par excellence, Hammamet séduit par ses plages de sable fin, sa médina historique et ses nombreux hôtels de luxe baignés de soleil méditerranéen.',
    shortDescription: 'Premier beach resort with a charming historic medina.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Hammamet_vue_g%C3%A9n%C3%A9rale.jpg/1280px-Hammamet_vue_g%C3%A9n%C3%A9rale.jpg',
    features: ['Plages', 'Médina', 'Jasmin Festival', 'Golf'],
    coordinates: { lat: 36.4000, lng: 10.6167 },
  },
  {
    id: '8',
    name: 'Tozeur',
    location: 'Tozeur',
    region: 'Sud-Ouest Tunisie',
    category: 'nature',
    rating: 4.7,
    reviews: 2100,
    price: '30-50 DT',
    duration: '2-3 jours',
    description: 'Oasis magique aux confins du désert, Tozeur est célèbre pour son architecture en briques de sable, ses palmeraies luxuriantes et ses gorges spectaculaires de Chebika et Mides.',
    shortDescription: 'Magical oasis city with unique brick architecture and gorges.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Tozeur%2C_Tunisia.jpg/1280px-Tozeur%2C_Tunisia.jpg',
    features: ['Palmeraie', 'Gorges de Chebika', 'Chott El Jerid', 'Architecture traditionnelle'],
    coordinates: { lat: 33.9197, lng: 8.1338 },
  },
];
