// styles.js - Premium Design Styles
import { StyleSheet, Platform } from 'react-native';
import { COLORS, SPACING, RADIUS, SHADOWS, IMAGE_HEIGHT } from './data';

export const styles = StyleSheet.create({
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.gray50 },
  loadingLogo: { width: 80, height: 80, borderRadius: 40, backgroundColor: COLORS.white, justifyContent: 'center', alignItems: 'center', ...SHADOWS.md },
  loadingText: { marginTop: 12, fontSize: 14, color: COLORS.gray500 },
  screen: { flex: 1, backgroundColor: COLORS.gray50 },
  header: { backgroundColor: COLORS.black, paddingHorizontal: SPACING.lg, paddingTop: Platform.OS === 'ios' ? 56 : 24, paddingBottom: SPACING.lg },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: SPACING.md },
  headerGreeting: { fontSize: 14, color: COLORS.gray400, marginBottom: 2 },
  headerTitle: { fontSize: 28, fontWeight: '700', color: COLORS.white, letterSpacing: -0.5 },
  headerSubtitle: { fontSize: 14, color: COLORS.gray400, marginTop: 2 },
  profileButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.15)', justifyContent: 'center', alignItems: 'center' },
  searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.white, borderRadius: RADIUS.full, paddingHorizontal: SPACING.md, paddingVertical: SPACING.sm, marginBottom: SPACING.md },
  searchContainerFocused: { borderWidth: 2, borderColor: COLORS.primary },
  searchInput: { flex: 1, fontSize: 16, color: COLORS.black, marginLeft: SPACING.sm, paddingVertical: SPACING.xs },
  categoriesContainer: { marginTop: SPACING.xs },
  categoriesContent: { paddingRight: SPACING.lg },
  categoryChip: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.15)', paddingHorizontal: SPACING.md, paddingVertical: SPACING.sm, borderRadius: RADIUS.full, marginRight: SPACING.sm, gap: 6 },
  categoryChipSelected: { backgroundColor: COLORS.white },
  categoryChipText: { fontSize: 14, fontWeight: '500', color: COLORS.gray300 },
  categoryChipTextSelected: { color: COLORS.black },
  listContent: { paddingHorizontal: SPACING.lg, paddingTop: SPACING.lg, paddingBottom: 120 },
  section: { marginBottom: SPACING.xl },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: SPACING.md },
  sectionTitle: { fontSize: 22, fontWeight: '600', color: COLORS.black, letterSpacing: -0.3 },
  sectionSubtitle: { fontSize: 13, color: COLORS.gray500, marginTop: 2 },
  sectionAction: { fontSize: 14, fontWeight: '500', color: COLORS.primary },
  cardWrapper: { marginBottom: SPACING.lg },
  card: { backgroundColor: COLORS.white, borderRadius: RADIUS.xl, overflow: 'hidden', ...SHADOWS.md },
  cardImageWrapper: { position: 'relative', height: IMAGE_HEIGHT },
  cardImage: { width: '100%', height: '100%' },
  favoriteButton: { position: 'absolute', top: SPACING.md, right: SPACING.md, width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.9)', justifyContent: 'center', alignItems: 'center', ...SHADOWS.sm },
  ratingBadge: { position: 'absolute', bottom: SPACING.md, left: SPACING.md, flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.white, paddingHorizontal: SPACING.sm, paddingVertical: SPACING.xxs, borderRadius: RADIUS.sm, gap: 4 },
  ratingText: { fontSize: 13, fontWeight: '600', color: COLORS.black },
  cardContent: { padding: SPACING.md },
  cardTitle: { fontSize: 18, fontWeight: '600', color: COLORS.black, marginBottom: SPACING.xxs, letterSpacing: -0.2 },
  locationRow: { flexDirection: 'row', alignItems: 'center', marginBottom: SPACING.xs, gap: 4 },
  cardLocation: { fontSize: 13, color: COLORS.gray500 },
  cardDescription: { fontSize: 14, color: COLORS.gray600, lineHeight: 20, marginBottom: SPACING.md },
  cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  reviewsText: { fontSize: 13, color: COLORS.gray500 },
  exploreButton: { backgroundColor: COLORS.primary, paddingHorizontal: SPACING.md, paddingVertical: SPACING.sm, borderRadius: RADIUS.sm },
  exploreButtonText: { fontSize: 13, fontWeight: '600', color: COLORS.white },
  smallCard: { width: 150, height: 180, marginRight: SPACING.md, borderRadius: RADIUS.lg, overflow: 'hidden', ...SHADOWS.md },
  smallCardImage: { width: '100%', height: '100%' },
  smallCardOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.2)' },
  smallFavoriteButton: { position: 'absolute', top: SPACING.sm, right: SPACING.sm, width: 28, height: 28, borderRadius: 14, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', alignItems: 'center' },
  smallCardContent: { position: 'absolute', bottom: SPACING.sm, left: SPACING.sm, right: SPACING.sm },
  smallCardTitle: { fontSize: 14, fontWeight: '600', color: COLORS.white, marginBottom: 2 },
  smallCardRating: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  smallCardRatingText: { fontSize: 11, fontWeight: '600', color: COLORS.white },
  emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: SPACING.xxxl, paddingHorizontal: SPACING.xl },
  emptyTitle: { fontSize: 20, fontWeight: '600', color: COLORS.black, marginTop: SPACING.md, marginBottom: SPACING.xs },
  emptySubtitle: { fontSize: 14, color: COLORS.gray500, textAlign: 'center', lineHeight: 20 },
  emptyButton: { backgroundColor: COLORS.primary, paddingHorizontal: SPACING.xl, paddingVertical: SPACING.md, borderRadius: RADIUS.full, marginTop: SPACING.xl },
  emptyButtonText: { fontSize: 15, fontWeight: '600', color: COLORS.white },
  mapContainer: { flex: 1, backgroundColor: COLORS.gray100 },
  mapPlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.gray100, margin: SPACING.lg, borderRadius: RADIUS.xl },
  mapPlaceholderTitle: { fontSize: 20, fontWeight: '600', color: COLORS.black, marginTop: SPACING.md },
  mapPlaceholderSubtitle: { fontSize: 14, color: COLORS.gray500, marginTop: SPACING.xs, textAlign: 'center', paddingHorizontal: SPACING.xl },
  mapMarkers: { position: 'absolute', bottom: SPACING.lg, left: 0, right: 0, paddingHorizontal: SPACING.lg },
  mapMarker: { alignItems: 'center', marginRight: SPACING.md },
  mapMarkerDot: { width: 14, height: 14, borderRadius: 7, backgroundColor: COLORS.mapMarker, borderWidth: 3, borderColor: COLORS.white, ...SHADOWS.sm },
  mapMarkerText: { fontSize: 11, fontWeight: '500', color: COLORS.black, backgroundColor: COLORS.white, paddingHorizontal: SPACING.sm, paddingVertical: SPACING.xxs, borderRadius: RADIUS.sm, marginTop: SPACING.xs, ...SHADOWS.sm },
  nearbySection: { paddingHorizontal: SPACING.lg, paddingBottom: 100, backgroundColor: COLORS.gray50 },
  detailScreen: { flex: 1, backgroundColor: COLORS.white },
  detailImageContainer: { height: 320 },
  detailImage: { width: '100%', height: '100%' },
  detailImageOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.05)' },
  detailBackButton: { position: 'absolute', top: Platform.OS === 'ios' ? 56 : 16, left: SPACING.lg, width: 40, height: 40, borderRadius: 20, backgroundColor: COLORS.white, justifyContent: 'center', alignItems: 'center', ...SHADOWS.md },
  detailShareButton: { position: 'absolute', top: Platform.OS === 'ios' ? 56 : 16, right: SPACING.lg + 48, width: 40, height: 40, borderRadius: 20, backgroundColor: COLORS.white, justifyContent: 'center', alignItems: 'center', ...SHADOWS.md },
  detailFavoriteButton: { position: 'absolute', top: Platform.OS === 'ios' ? 56 : 16, right: SPACING.lg, width: 40, height: 40, borderRadius: 20, backgroundColor: COLORS.white, justifyContent: 'center', alignItems: 'center', borderWidth: 1.5, borderColor: COLORS.primary, ...SHADOWS.md },
  detailFavoriteButtonActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  detailContent: { padding: SPACING.lg, paddingBottom: SPACING.xxxl },
  detailTitleSection: { marginBottom: SPACING.md },
  detailCategory: { fontSize: 12, fontWeight: '600', color: COLORS.primary, textTransform: 'uppercase', letterSpacing: 1, marginBottom: SPACING.xs },
  detailTitle: { fontSize: 28, fontWeight: '700', color: COLORS.black, letterSpacing: -0.5, marginBottom: SPACING.xs },
  detailLocationRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  detailLocation: { fontSize: 14, color: COLORS.gray500 },
  detailRatingRow: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm },
  detailRatingBadge: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  detailRatingValue: { fontSize: 16, fontWeight: '600', color: COLORS.black },
  detailReviews: { fontSize: 14, color: COLORS.gray500 },
  divider: { height: 1, backgroundColor: COLORS.gray100, marginVertical: SPACING.lg },
  detailSection: { marginBottom: SPACING.lg },
  detailSectionTitle: { fontSize: 18, fontWeight: '600', color: COLORS.black, marginBottom: SPACING.sm },
  detailDescription: { fontSize: 15, color: COLORS.gray600, lineHeight: 24 },
  infoCardsRow: { flexDirection: 'row', gap: SPACING.md, marginBottom: SPACING.xl },
  infoCard: { flex: 1, backgroundColor: COLORS.gray50, borderRadius: RADIUS.lg, padding: SPACING.lg, alignItems: 'center' },
  infoCardLabel: { fontSize: 12, color: COLORS.gray500, marginTop: SPACING.sm, marginBottom: 2 },
  infoCardValue: { fontSize: 14, fontWeight: '600', color: COLORS.black },
  actionButtons: { flexDirection: 'row', gap: SPACING.md },
  primaryButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.primary, paddingVertical: SPACING.md, borderRadius: RADIUS.md, gap: SPACING.sm, ...SHADOWS.md },
  primaryButtonDisabled: { opacity: 0.7 },
  primaryButtonText: { fontSize: 16, fontWeight: '600', color: COLORS.white },
  secondaryButton: { width: 52, height: 52, borderRadius: RADIUS.md, backgroundColor: COLORS.gray50, borderWidth: 1, borderColor: COLORS.gray200, justifyContent: 'center', alignItems: 'center' },
  authContainer: { flex: 1, backgroundColor: COLORS.white },
  authContent: { flex: 1 },
  authHeader: { alignItems: 'center', paddingTop: SPACING.xl, paddingBottom: SPACING.xl, paddingHorizontal: SPACING.lg },
  authLogo: { width: 72, height: 72, borderRadius: 36, backgroundColor: COLORS.gray50, justifyContent: 'center', alignItems: 'center', marginBottom: SPACING.lg, ...SHADOWS.sm },
  authTitle: { fontSize: 28, fontWeight: '700', color: COLORS.black, letterSpacing: -0.5, marginBottom: SPACING.xs },
  authSubtitle: { fontSize: 15, color: COLORS.gray500 },
  authForm: { paddingHorizontal: SPACING.lg, flex: 1 },
  backButton: { padding: SPACING.md },
  inputGroup: { marginBottom: SPACING.md },
  inputLabel: { fontSize: 13, fontWeight: '500', color: COLORS.gray700, marginBottom: SPACING.xs },
  inputContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.gray50, borderRadius: RADIUS.md, paddingHorizontal: SPACING.md },
  input: { flex: 1, fontSize: 16, color: COLORS.black, paddingVertical: SPACING.md, marginLeft: SPACING.sm },
  dividerContainer: { flexDirection: 'row', alignItems: 'center', marginVertical: SPACING.lg },
  dividerLine: { flex: 1, height: 1, backgroundColor: COLORS.gray200 },
  dividerText: { fontSize: 13, color: COLORS.gray400, marginHorizontal: SPACING.md },
  socialButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.gray200, paddingVertical: SPACING.md, borderRadius: RADIUS.md, gap: SPACING.sm },
  socialButtonText: { fontSize: 15, fontWeight: '500', color: COLORS.gray700 },
  switchAuthButton: { alignItems: 'center', marginTop: SPACING.xl },
  switchAuthText: { fontSize: 14, color: COLORS.gray500 },
  switchAuthLink: { color: COLORS.primary, fontWeight: '600' },
  tabBar: { position: 'absolute', backgroundColor: COLORS.white, borderTopWidth: 0, height: Platform.OS === 'ios' ? 88 : 68, paddingBottom: Platform.OS === 'ios' ? 28 : 8, paddingTop: 8, borderRadius: RADIUS.xl, left: 16, right: 16, bottom: 16, ...SHADOWS.xl },
  tabBarLabel: { fontSize: 11, fontWeight: '500', marginTop: 2 },
  tabBarBadge: { backgroundColor: COLORS.primary, fontSize: 10, fontWeight: '600', minWidth: 18, height: 18, borderRadius: 9 },
});